isEnableClassical=true
isEnablePBE=true
isEnableSignature=true
isEnableMac=true
isEnableSymmetricStream=true
isEnableQrcode=true
isEnableInternalWebview=true
extUrls=http://www.hiencode.com/,https://tool.lu/,https://www.sojson.com/encrypt_rabbit.html,https://www.qqxiuzi.cn/bianma/wenbenjiami.php,https://github.com/Leon406/ToolsFx